#!/bin/sh

# sendmail-mini
# A sendmail replacement for local (single machine) mail delivery.
# Usefull when only crond and similar system services want to use sendmail, 
# or a full MTA is not otherwise needed or desired.

PARAMS="$@"

# Hard code the receiver.  Could read from command line, but this script is 
# intended for single-user systems.
RECEIVER=mobusby

SYSMBOX=/var/spool/mail
mkdir -p $SYSMBOX
SYSMBOX=$SYSMBOX/$RECEIVER

# The magic "From_ line" (mbox format)
FROMLINE="From `whoami` `date +%c`"
echo $FROMLINE >> $SYSMBOX

# Forward stdin to the mbox file
cat >> $SYSMBOX

# add a custom footer, so we know this script was used
echo "" >> $SYSMBOX
echo "----------" >> $SYSMBOX
echo "Sent using sendmail-mini,"
echo "http://www.BusbyCreations.com/apps/#sendmail-mini"
echo "sendmail params: $PARAMS" >> $SYSMBOX

# add a blank line to separate from next message (mbox format)
echo "" >> $SYSMBOX

