#!/bin/sh

# sendmail-mini
# A sendmail replacement for local (single machine) mail delivery.
# Usefull when only crond and similar system services want to use sendmail, 
# or a full MTA is not otherwise needed or desired.
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# sendmail-mini is licensed under the New BSD License (3-clause BSD   #
# License)                                                            #
#                                                                     #
# Copyright (c) 2012, Mark Busby <mark .at. BusbyCreations .dot. com> #
# All rights reserved.                                                #
#                                                                     #
# Redistribution and use in source and binary forms, with or without  #
# modification, are permitted provided that the following conditions  #
# are met:                                                            #
#   - Redistributions of source code must retain the above copyright  #
#     notice, this list of conditions and the following disclaimer.   #
#   - Redistributions in binary form must reproduce the above         #
#     copyright notice, this list of conditions and the following     #
#     disclaimer in the documentation and/or other materials provided #
#     with the distribution.                                          #
#   - Neither the name of Mark Busby nor Busby Creations nor the      #
#     names of its contributors may be used to endorse or promote     #
#     products derived from this software without specific prior      #
#     written permission.                                             #
#                                                                     #
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS #
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT   #
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS   #
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE      #
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,          #
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES  #
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR  #
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)  #
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, # 
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)       #
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED #
# OF THE POSSIBILITY OF SUCH DAMAGE.                                  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

PARAMS="$@"

# Hard code the receiver.  Could read from command line, but this script is 
# intended for single-user systems.
RECEIVER=mobusby

SYSMBOX=/var/spool/mail
mkdir -p $SYSMBOX
SYSMBOX=$SYSMBOX/$RECEIVER

# The magic "From_ line" (mbox format)
FROMLINE="From `whoami` `date +%c`"
echo $FROMLINE >> $SYSMBOX

# Forward stdin to the mbox file
cat >> $SYSMBOX

# add a custom footer, so we know this script was used
echo "" >> $SYSMBOX
echo "----------" >> $SYSMBOX
echo "Sent using sendmail-mini," >> $SYSMBOX
echo "http://www.BusbyCreations.com/apps/#sendmail-mini" >> $SYSMBOX
echo "sendmail params: $PARAMS" >> $SYSMBOX

# add a blank line to separate from next message (mbox format)
echo "" >> $SYSMBOX

